sudo: true
dist: trusty

language: python
python:
  - "3.4"

install:
 - pip install pylint
 - pip install .

script:
  - ./functional_tests/biodemopython-test.sh -p biodemopython -d functional_tests/test_data
  - ./.travis/unit-test.sh
